on:
  workflow_dispatch:
  push:
    branches: main

name: Quarto Publish

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install jupyter
        run: python3 -m pip install jupyterlab==3.6.0 pandas==1.5.3 numpy==1.24

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - name: Install rmarkdown
        run: install.packages("rmarkdown");install.packages("ggplot2")
        shell: Rscript {0}

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
